// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Route, Routes } from "react-router-dom";
import NavBar from "./component/NavBar";
import HotKeyProvider from "./component/Hotkeys";
import TTSBar from "./component/TTSBar";
import { TextSizeProvider } from "./context/textsizecontext"; 
import { TTSProvider } from './context/TTSContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NoTreble",
  description: "Generated by create next app [CHANGE ME]",
};

function Header() {
  return (
    <>
      <NavBar className="nav-bar" />
    </>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <TTSProvider>
          <TextSizeProvider>
            <Header />
            <HotKeyProvider />
            <TTSBar />
            {children}
          </TextSizeProvider>
        </TTSProvider>
      </body>
    </html>
  );
}
